use_frameworks!

platform :ios, '10.0'

target 'SmartLogs_Example' do
  pod 'SmartLogs', :path => '../'
  pod 'SSZipArchive', '~> 2.4.2'

  target 'SmartLogs_Tests' do
    inherit! :search_paths

    
  end
end
