use_frameworks!

platform :ios, '10.0'

target 'SmartLog_Example' do
  pod 'SmartLog', :path => '../'
  pod 'SSZipArchive', '~> 2.4.2'
  
  target 'SmartLog_Tests' do
    inherit! :search_paths

    
  end
end
